# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-08 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='com_date',
        ),
        migrations.AddField(
            model_name='comtent',
            name='com_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
